version: '3.4'

services:
  b:
    image: b
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8457:8457
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "api.js"]
